#!/bin/bash

# Get all files ending in .d2
for file in $(find . -name "*.d2"); do
    # Get the filename without the extension
    filename=$(basename $file .d2)

    d2 $file output/$filename.png
done